### ISSUE TITLE
libmarkdown.vapi: error: Inline allocated array as field requires to have fixed length

### ISSUE THREAD

**Issue by tim77** [Philip-Scott/Notes-up#361]
Notes-up won't compile during mass rebuild with new Vala on Fedora Rawhide (33).

- [Koji task](https://koji.fedoraproject.org/koji/taskinfo?taskID=48185162)
- [Koji build log](https://kojipkgs.fedoraproject.org//work/tasks/5162/48185162/build.log)

## Expected Behavior
Should successfully compiles as before.

## Current Behavior
```vala
[  4%] Built target i18n
webkit2gtk-4.0.vapi:247.4-247.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
webkit2gtk-4.0.vapi:249.4-249.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
webkit2gtk-4.0.vapi:252.4-252.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
webkit2gtk-4.0.vapi:254.4-254.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
webkit2gtk-4.0.vapi:257.4-257.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
webkit2gtk-4.0.vapi:259.4-259.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
webkit2gtk-4.0.vapi:262.4-262.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
webkit2gtk-4.0.vapi:264.4-264.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
libmarkdown.vapi:44.2-44.31: error: Inline allocated array as field requires to have fixed length
	public char markdown_version[];
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/builddir/build/BUILD/Notes-up-2.0.2/src/Services/Image.vala:84.9-84.70: warning: unhandled error `GLib.Error'
        var file_info = file.query_info ("*", FileQueryInfoFlags.NONE);
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/builddir/build/BUILD/Notes-up-2.0.2/src/Services/Image.vala:115.13-115.82: warning: unhandled error `GLib.FileError'
            GLib.FileUtils.get_contents (file.get_path (), out data_raw, out size);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/builddir/build/BUILD/Notes-up-2.0.2/src/Plugins/PageLink.vala:57.20-65.14: warning: unhandled error `GLib.RegexError'
/builddir/build/BUILD/Notes-up-2.0.2/src/Plugins/PageLink.vala:27.17-27.60: warning: unhandled error `GLib.RegexError'
        regex = new Regex ("<page\\s([0-9]+)\\s([^>]{1,})>");
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/builddir/build/BUILD/Notes-up-2.0.2/src/Widgets/Viewer.vala:72.13-72.23: warning: `null' incompatible with return type `Gtk.Widget'
            return null;
            ^^^^^^^^^^^
/builddir/build/BUILD/Notes-up-2.0.2/src/Widgets/Viewer.vala:79.41-79.91: warning: Access to possible `null'. Perform a check or use an unsafe cast.
                        launch_browser ((decision as WebKit.ResponsePolicyDecision).request.get_uri ());
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/builddir/build/BUILD/Notes-up-2.0.2/src/Services/WordWrapper.vala:33.50-33.98: warning: unhandled error `GLib.RegexError'
        WordWrapper.starting_whitespaces_regex = new Regex ("^(\\s)+", RegexCompileFlags.EXTENDED);
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/builddir/build/BUILD/Notes-up-2.0.2/src/Services/WordWrapper.vala:34.48-34.96: warning: unhandled error `GLib.RegexError'
        WordWrapper.ending_whitespaces_regex = new Regex ("(\\s)+$", RegexCompileFlags.EXTENDED);
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/builddir/build/BUILD/Notes-up-2.0.2/src/GranitePatches/SourceList.vala:1516.17-1516.33: warning: `Granite.Widgets.Utils.set_theming' has been deprecated since 5.5.0. Use 
/builddir/build/BUILD/Notes-up-2.0.2/src/GranitePatches/SourceList.vala:1516.62-1516.91: warning: `Granite.StyleClass.SOURCE_LIST' has been deprecated since 0.4.2. Use Granite.STYLE_CLASS_SOURCE_LIST
/builddir/build/BUILD/Notes-up-2.0.2/src/Widgets/Headerbar.vala:54.9-54.49: warning: Access to possible `null'. Perform a check or use an unsafe cast.
        (entry as Gtk.SearchEntry).search_changed.connect(() => {
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/builddir/build/BUILD/Notes-up-2.0.2/src/Widgets/Editor.vala:311.9-311.31: warning: `Gtk.Widget.override_font' has been deprecated since 3.16
Command-line option `--thread` is deprecated and will be ignored
Compilation failed: 1 error(s), 20 warning(s)
gmake[2]: *** [CMakeFiles/com.github.philip-scott.notes-up.dir/build.make:127: src/Main.c] Error 1
gmake[2]: Leaving directory '/builddir/build/BUILD/Notes-up-2.0.2/x86_64-redhat-linux-gnu'
gmake[1]: *** [CMakeFiles/Makefile2:160: CMakeFiles/com.github.philip-scott.notes-up.dir/all] Error 2
gmake[1]: Leaving directory '/builddir/build/BUILD/Notes-up-2.0.2/x86_64-redhat-linux-gnu'
```

## Your Environment (for bugs)

- Notes-Up Version: 2.0.2
- OS Info: Fedora Rawhide (33)
- Vala: 0.48.8
- GCC: 10.2.1

**Comment by Philip-Scott** [comment]
The main branch currently compiles correctly on Vala 0.48.9. Please let me know if you still have issues :)

**Comment by tim77** [comment]
@Philip-Scott thanks, can confirm, main branch compiles and works.

Can you please tag a new version and i can push latest and greatest in repos? :) Or if you consider current main branch stable enough i can push it without new tag. But this is usually discouraged by distros policies, so that's why i ask.

**Comment by davidak** [comment]
It is also broken in NixOS. Can you make a new release?
